### ISSUE TITLE
Jump and mem in F32a

### ISSUE THREAD

**Issue by guganchik** [ryukzak/wrench#18]
Version 0.0.0.4 (5491c25) Wed Dec 4 00:18:18 2024
	

## Name:

			bug_1

## Assembler Code:
	.data

	input_addr:        .word 0x80
	output_addr:       .word 0x84

	.text

	_start:
		@p input_addr a! @
		summator                                  \ THIS IS OUR JUMP
		@p output_addr a! !
		halt

	summator:
		lit 25
		+
		;

## Config (YAML):

		name: "bug"
	limit: 100
	memory_size: 0x1000
	input_streams:
	    0x80: [24]
	    0x84: []
	reports:
	    - name: Step-by-step log
	      slice: all
	      filter:
	          - instruction
	          - state
	      inspector:
	          - - T A B S
	            - [register, T]
	            - [register, A]
	            - [register_hex, B]
	            - [register, S]
	            - R
	            - [register, R]
	          - - [memory_cells, 0x80, 0x88]
	    - name: Check results
	      slice: last
	      filter:
	          - state
	      inspector:
	          - ["numio[0x80]:", [number_io_stream, 0x0080]]
	          - ["numio[0x84]:", [number_io_stream, 0x0084]]
	      assert: |
	          numio[0x80]: [] >>> [0]
	          numio[0x84]: [] >>> [49]

##  logger:
	# Step-by-step log
	8:      FetchP 0        @_start ;;
	T A B S 128 0 0x00000000 0 R 0
	mem[128..136]:  00 00 00 00 00 00 00 00 00 ;;
	16:     AStore ;;
	T A B S 0 128 0x00000000 0 R 0
	mem[128..136]:  00 00 00 00 00 00 00 00 00 ;;
	20:     Fetch ;;
	T A B S 24 128 0x00000000 0 R 0
	mem[128..136]:  00 00 00 00 00 00 00 00 00 ;;
	24:     Call 48 ;;
	T A B S 24 128 0x00000000 0 R 24
	mem[128..136]:  00 00 00 00 00 00 00 00 00 ;;
	48:     Lit 25          @summator ;;
	T A B S 25 128 0x00000000 24 R 24
	mem[128..136]:  00 00 00 00 00 00 00 00 00 ;;
	52:     Add ;;
	T A B S 49 128 0x00000000 0 R 24
	mem[128..136]:  00 00 00 00 00 00 00 00 00 ;;
	56:     Return ;;
	T A B S 49 128 0x00000000 0 R 0
	mem[128..136]:  00 00 00 00 00 00 00 00 00 ;;
	28:     FetchP 4 ;;
	T A B S 132 128 0x00000000 49 R 0
	mem[128..136]:  00 00 00 00 00 00 00 00 00 ;;
	36:     AStore ;;
	T A B S 49 132 0x00000000 0 R 0
	mem[128..136]:  00 00 00 00 00 00 00 00 00 ;;
	40:     Store ;;
	T A B S 0 132 0x00000000 0 R 0
	mem[128..136]:  00 00 00 00 00 00 00 00 00 ;;
	44:     Halt ;;
	T A B S 0 132 0x00000000 0 R 0
	mem[128..136]:  00 00 00 00 00 00 00 00 00
	---
	# Check results
	numio[0x80]: [] >>> []
	numio[0x84]: [] >>> [49]

# Problem:
if we make a jump based on an Isa, we will have the problem that it is interpreted as jmp + return
our asm code:
		
		.data

	input_addr:        .word 0x80
	output_addr:       .word 0x84

	.text

	_start:
		@p input_addr a! @
		summator ;
		@p output_addr a! !
		halt

	summator:
		lit 25
		+
		;

I think we needn't to fix interpretation... But we can change out jump to ONLY:
		
			REF
			
			
And also I don't understand why we can't see the value in memory that we set in yaml. I think this is important so that it is convenient to debug the code.

You can see it here:

	8:      FetchP 0        @_start ;;
	T A B S 128 0 0x00000000 0 R 0
	mem[128..136]:  00 00 00 00 00 00 00 00 00 ;;

**Comment by ryukzak** [comment]
Not reproduce:

- `label` -- call
- `label ;` -- jmp

```shell
10:36 wrench (master) ✗ cat example/f32a/jmp_18.s
.text

_start:
    lit 25
    lit 25
    call
    jmp ;

call:
    + ;

jmp:
    halt
10:36 wrench (master) ✗ stack build --fast && stack exec wrench -- example/f32a/jmp_18.s -c example/f32a/jmp_18.yaml --isa f32a -S
0:	_start
16:	call
24:	jmp
---
mem[0..3]: 	Lit 25 	@_start
mem[4..7]: 	Lit 25
mem[8..11]: 	Call 16
mem[12..15]: 	Jump 24
mem[16..19]: 	Add 	@call
mem[20..23]: 	Return
mem[24..27]: 	Halt 	@jmp
mem[28..4095]: 	( 00 )
10:36 wrench (master) ✗ stack build --fast && stack exec wrench -- example/f32a/jmp_18.s -c example/f32a/jmp_18.yaml --isa f32a
# Step-by-step log
0:	Lit 25  	@_start
4:	Lit 25
8:	Call 16
16:	Add  	@call
20:	Return
12:	Jump 24
24:	Halt  	@jmp
---
# Check results
T A B S 50 0 0x00000000 0
```
