### ISSUE TITLE
Problems with Data Section

### ISSUE THREAD

**Issue by guganchik** [ryukzak/wrench#19]
Version 0.0.0.4 (5491c25) Wed Dec 4 00:18:18 2024
for a better user experience, I uploaded it directly to the server
If we not use "alligment (http://wrench.edu.swampbuds.me/result/294a8c7d-6d28-4ab3-acec-ef886a90da55)
## We can see:

			T A B S 10 128 0x00000088 12 R 28
		mem[136..139]: 	If 172 <------------------- if sum_digits_end
		mem[140..143]: 	AStore <------------------- a!
		mem[144..147]: 	Lit 0 <-------------------- lit 0
		mem[148..151]: 	Lit 0 <-------------------- lit 0
		mem[152..155]: 	Call 52 ;; <--------------- div (all of this instruction we can se in section sum_digits_loop)
		116:	StoreB ;;
		T A B S 12 128 0x00000088 0 R 28
		mem[136..139]: 	0a 00 00 00 <--------- In this moment, we store B, and the comand has been wiped out
		mem[140..143]: 	AStore
		mem[144..147]: 	Lit 0
		mem[148..151]: 	Lit 0
		mem[152..155]: 	Call 52 ;;				
		
## Our	error		
		wrench.EXE: Can't read instruction from input port: 128
		CallStack (from HasCallStack):
		  error, called at src\Relude\Debug.hs:296:11 in relude-1.2.1.0-A3pSnvjPTxTBRLw40rZFlT:Relude.Debug
		  error, called at src\Machine\Memory.hs:143:23 in wrench-0.0.0.4-5qkvt0twA87FHD6Umac09m:Machine.Memory

## If we add aligment:
http://wrench.edu.swampbuds.me/result/2a86cf7b-15b0-4e9c-9cc0-c85c2f97f32c

	240:	BStore ;;
	T A B S 10 128 0x00000088 12 R 156
	mem[136..139]: 	2e 00 00 00 <-------------------- It is symbol "."
	mem[140..147]: 	FetchP 0
	mem[148..151]: 	AStore
	mem[152..155]: 	Fetch ;;
	244:	StoreB ;;
	T A B S 12 128 0x00000088 0 R 156
	mem[136..139]: 	0a 00 00 00 <-------------------- We rewrite it to our devisor
	mem[140..147]: 	FetchP 0
	mem[148..151]: 	AStore
	mem[152..155]: 	Fetch ;;
	248:	FetchP 8  	@sum_digits_loop ;;
	T A B S 136 128 0x00000088 12 R 156
	mem[136..139]: 	0a 00 00 00
	mem[140..147]: 	FetchP 0
	mem[148..151]: 	AStore
	mem[152..155]: 	Fetch ;;

## Output of program

---
	# Check results
	numio[0x80]: [] >>> []
	numio[0x84]: [] >>> [3]
That's OK.

**Comment by ryukzak** [comment]
It is not a problem, it is an expected behaviour. Why -- good question for the lab.
