### ISSUE TITLE
No symIO for Task (String in numio)

### ISSUE THREAD

**Issue by guganchik** [ryukzak/wrench#8]
Version 0.0.0.1 (f0a992b) Mon Oct 7 21:59:51 2024

Like in example with Hello.s we need to check numio (codes of symb) and symio
(with hello.s this ticket works)
My creddits:
	

## Variant:

			is_prime

## Assembler Code:
	    .data
	input_addr:    .word 0x80  
	output_addr:   .word 0x84
	buff:         .byte 'FalseTrue     '

	    .text
	_start:

	    lui      t0, input_addr 
	    addi     t0, t0, input_addr
	    lw       t0, 0(t0)
	    lw       t1, 0(t0)

	    li       t2, 1               ; t2 = 1
	    bgt      t2, t1, invalid_input 

	    li       t2, 2               ; t2 = 2

	check_prime_loop:
	    mul      t3, t2, t2
	    bgt      t3, t1, prime 

	    rem      t4, t1, t2
	    beqz     t4, composite

	    addi     t2, t2, 1 
	    j        check_prime_loop

	composite:
	    addi     t5, t5, buff
	    li       t2, 5
	    j        write_output

	prime:
	    addi     t5, t5, buff
	    addi     t5, t5, 5
	    li       t2, 4
	    j        write_output

	invalid_input:
	    addi     t5, t5, buff
	    li       t2, 5
	    j        write_output

	write_output:
	    lui      t0, output_addr
	    addi     t0, t0, output_addr
	    lw       t0, 0(t0)

	while:
	    beqz    t2, end              ; while (acc != 0) {
	    addi    t2, t2, -1           ;   n--

	    lw      t6, 0(t5)            ;   tmp = *buf
	    sb      t6, 0(t0)            ;   *output_addr = tmp;

	    addi    t5, t5, 1            ;   ptr++

	    j while                      ; }

	end:
	    halt
## Config (YAML):

	limit: 1000
	memory_size: 1000
	input_streams:
	  0x80: [4]
	  0x84: []
	reports:
	  - name: Check results
	    slice: last
	    filter:
	      - state
	    inspector:
	      - ["numio[0x80]:", [number_io_stream, 0x0080]]
	      - ["numio[0x84]:", [number_io_stream, 0x0084]]
	      - ["symio[0x80]:", [symbol_io_stream, 0x0080]]
	      - ["symio[0x84]:", [symbol_io_stream, 0x0084]]
	    assert: |
	      numio[0x80]: [] >>> []
	      numio[0x84]: [] >>> [70,97,108,115,101]
	      symio[0x80]: "" >>> ""
	      symio[0x84]: "" >>> "False"

## ## Failed Test Case:
	name: "assert is_prime(*(8,)) == (False,)"
	limit: 1000
	memory_size: 0x1000
	input_streams:
	  0x80: [8]
	  0x84: []
	reports:
	  - name: Check results
	    slice: last
	    filter:
	      - state
	    inspector:
	      - ["numio[0x80]:", [number_io_stream, 0x0080]]
	      - ["numio[0x84]:", [number_io_stream, 0x0084]]

	    assert: |
	      numio[0x80]: [] >>> []
	      numio[0x84]: [] >>> [False]

	===

	#Check results
		numio[0x80]: [] >>> []
		numio[0x84]: [] >>> [70,97,108,115,101]

		ASSERTION FAIL, expect:
		numio[0x80]: [] >>> []
		numio[0x84]: [] >>> [False]

		Diff:
		2c2
		< numio[0x84]: [] >>> [70,97,108,115,101]
		---
		> numio[0x84]: [] >>> [False]

**Comment by ryukzak** [comment]
Looks like it is an issue in test case. I generate them from Python, and boolean represent as True or False. But it should be 1 and 0.

Will fix it soon.
